#!/usr/bin/env python3
"""
embed_files.py — generate a C header containing the contents of web/ as
byte arrays, plus a lookup table.

Usage: embed_files.py <web_dir> <output_header>

The generated header defines:
  STATIC_FILES_COUNT
  STATIC_FILES[]   (static_file_t)

Content-Type is sniffed from file extension. Anything unknown is shipped as
'application/octet-stream'.
"""
import os
import sys
from pathlib import Path

MIME = {
    ".html": "text/html; charset=utf-8",
    ".htm":  "text/html; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".mjs":  "application/javascript; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg":  "image/svg+xml",
    ".png":  "image/png",
    ".ico":  "image/x-icon",
    ".woff2": "font/woff2",
    ".woff": "font/woff",
    ".ttf":  "font/ttf",
    ".map":  "application/json; charset=utf-8",
    ".txt":  "text/plain; charset=utf-8",
}

def c_byte_array(data: bytes, varname: str) -> str:
    """Render a `static const unsigned char NAME[] = { ... };` line."""
    parts = [f"static const unsigned char {varname}[] = {{"]
    line = "    "
    for i, b in enumerate(data):
        line += f"0x{b:02x},"
        if (i + 1) % 16 == 0:
            parts.append(line)
            line = "    "
    if line.strip():
        parts.append(line)
    parts.append("};")
    return "\n".join(parts)

def safe_c_ident(s: str) -> str:
    out = []
    for ch in s:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    return "".join(out)

def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <web_dir> <out_header>", file=sys.stderr)
        return 2

    web_dir = Path(sys.argv[1]).resolve()
    out     = Path(sys.argv[2]).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    if not web_dir.is_dir():
        print(f"web dir not found: {web_dir}", file=sys.stderr)
        return 2

    files = []
    for root, _, names in os.walk(web_dir):
        for n in names:
            p = Path(root) / n
            files.append(p)
    files.sort()

    chunks = []
    table  = []
    for i, p in enumerate(files):
        rel = "/" + str(p.relative_to(web_dir)).replace(os.sep, "/")
        data = p.read_bytes()
        ext = p.suffix.lower()
        mime = MIME.get(ext, "application/octet-stream")
        var  = f"sf_{i}_{safe_c_ident(rel)}"
        chunks.append(c_byte_array(data, var))
        table.append(
            f'    {{ "{rel}", "{mime}", {var}, sizeof({var}) }},'
        )

    header = []
    header.append("/* AUTO-GENERATED by tools/embed_files.py — do not edit by hand. */")
    header.append("#pragma once")
    header.append("#include \"static_files.h\"")
    header.append("")
    header.extend(chunks)
    header.append("")
    header.append("static const static_file_t STATIC_FILES[] = {")
    header.extend(table)
    header.append("};")
    header.append(f"#define STATIC_FILES_COUNT (sizeof(STATIC_FILES)/sizeof(STATIC_FILES[0]))")
    header.append("")

    out.write_text("\n".join(header), encoding="utf-8")
    print(f"embedded {len(files)} file(s) → {out}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
