#include "static_files.h"

/* This header is generated by tools/embed_files.py at build time.
 * It defines: STATIC_FILES_COUNT and STATIC_FILES[STATIC_FILES_COUNT]. */
#include "web_static.h"

#include <string.h>

const static_file_t *static_files_get(const char *path) {
    if (path == NULL) return NULL;
    /* normalize "/" → "/index.html" */
    if (path[0] == '/' && path[1] == '\0') path = "/index.html";

    for (size_t i = 0; i < STATIC_FILES_COUNT; ++i) {
        if (strcmp(STATIC_FILES[i].path, path) == 0) return &STATIC_FILES[i];
    }
    return NULL;
}
